### ISSUE TITLE
isomorƒ

### ISSUE THREAD

**Issue by slavakurilyak** [ivanreese/visual-programming-codex#43]
Please add [isomorƒ](https://isomorf.io/) to your repo. 

isomorƒ is a `visual programming environment for cloud services`

[![isomorf-welcome-12fc8a5dd1](https://user-images.githubusercontent.com/6625584/70478852-ed798b80-1a90-11ea-925e-8c5ad40d479c.png)](https://isomorf.io/))

**Comment by ivanreese** [comment]
I believe I had isomorf included at one point, but removed it because there's nothing actually visual about what they're making. Their environment is a traditional text-based editor, with an arbitrary choice of syntax for the language. Can you point me to any indication of what they're doing that counts as "visual"?

**Comment by slavakurilyak** [comment]
Check out [An Experiment in Structured Code Editing](https://blog.isomorf.io/an-experiment-in-structured-code-editing-68b917a9157c) by @aaron-m-kent

**Comment by ivanreese** [comment]
> Despite the structure and visualization of code, the intent is NOT to move coding toward a visual mouse-click style input paradigm.

This is a structured / projectional editor, which is a nice improvement over plain text editing. But it's not doing much with respect to visual communication. There are no graphics, nothing spatial, no animation, no live coding.

The work they're doing is good, and I support it and have long been excited to see them succeed. But I don't believe it fits within the theme of my collection.
